#!/usr/bin/env bash

set -e

cd "$(dirname "$0")"

mkdir -p workspace

OPENAI_API_KEY_FILE="${PWD}/openai_api.key"

if ! [[ -f "${OPENAI_API_KEY_FILE}" ]]; then
  read -r -p 'Enter openai api key (https://platform.openai.com/api-keys): ' OPENAI_API_KEY
  touch "${OPENAI_API_KEY_FILE}"
  chmod 600 "${OPENAI_API_KEY_FILE}"
  printf '%s\n' "${OPENAI_API_KEY}" > "${OPENAI_API_KEY_FILE}"
fi

read -r OPENAI_API_KEY < "${OPENAI_API_KEY_FILE}"
export OPENAI_API_KEY
trap 'docker rm -f "aider_${USER}"' EXIT
docker build -t aider .
docker run --rm -d -u "$(id -u):$(id -g)" -e OPENAI_API_KEY -v "${PWD}/workspace:/workspace" --name "aider_${USER}" aider
docker exec -u root "aider_${USER}" adduser -d /workspace -M -u "$(id -u)" "${USER}"
docker exec "aider_${USER}" pip install --user aider-chat
printf '\n'
docker exec "aider_${USER}" bash -c 'printf "Node version:" && node -v && python --version && aider --version'
printf 'Openai api key is stored in "%s"\n' "${OPENAI_API_KEY_FILE}"
printf '\n'
docker exec -ti "aider_${USER}" bash
