#!/usr/bin/env bash

set -e

cd "$(dirname "$0")"

mkdir -p workspace

OPENAI_API_KEY_FILE="${PWD}/openai_api.key"

if ! [[ -f "${OPENAI_API_KEY_FILE}" ]]; then
  read -r -p 'Enter openai api key (https://platform.openai.com/api-keys): ' OPENAI_API_KEY
  touch "${OPENAI_API_KEY_FILE}"
  chmod 600 "${OPENAI_API_KEY_FILE}"
  printf '%s\n' "${OPENAI_API_KEY}" > "${OPENAI_API_KEY_FILE}"
fi

read -r OPENAI_API_KEY < "${OPENAI_API_KEY_FILE}"
export OPENAI_API_KEY
trap 'docker rm -f "aider_golin_${USER}"' EXIT
docker build -t aider_golin .
docker run --rm -d -u "$(id -u):$(id -g)" -e OPENAI_API_KEY -v "${PWD}/workspace:/workspace" --name "aider_golin_${USER}" aider_golin
docker exec -u root "aider_golin_${USER}" adduser -D -h /workspace -H -u "$(id -u)" "${USER}"
printf '\n'
docker exec "aider_golin_${USER}" bash -c 'python --version && aider --version'
docker exec "aider_golin_${USER}" git config --global user.name "$(git config --global user.name)"
docker exec "aider_golin_${USER}" git config --global user.email "$(git config --global user.email)"
printf 'Git configuration:\n'
docker exec "aider_golin_${USER}" git config --global user.name
docker exec "aider_golin_${USER}" git config --global user.email
printf 'Openai api key is stored in "%s"\n' "${OPENAI_API_KEY_FILE}"
printf '\n'
docker exec -ti "aider_golin_${USER}" bash
